---
title: "Exercícios"
---

```{r, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```

<script src="https://cdn.datacamp.com/datacamp-light-latest.min.js"></script>

```{r, include=FALSE}

library(forcats)

f1 <- factor(letters)
f2 <- fct_relevel(f1, rev(letters))
f3 <- lvls_revalue(f1, rev(letters))

tutorial::go_interactive()
```

1. Transforme o fator `f1` no fator `f2`.

```{r, eval = T}

print(f2)

```

```{r ex="exercicio_01", type="sample-code"}
# Digite o código aqui
```

```{r ex="exercicio_01", type="solution"}
fct_relevel(f1, rev(letters))
```

```{r ex="exercicio_01", type="sct"}
test_output_contains("f2", incorrect_msg = "Tem certeza de que indicou a expressão corretamente?")
success_msg("Correto!")
```

2. Transforme o fator `f1` no fator `f3`.

```{r, eval = T}

print(f3)

```

```{r ex="exercicio_02", type="solution"}
lvls_revalue(f1, rev(letters))
```

```{r ex="exercicio_01", type="sct"}
test_output_contains("f3", incorrect_msg = "Tem certeza de que indicou a expressão corretamente?")
success_msg("Correto!")
```
